[book]
authors = ["ronmkr"]
language = "en"
src = "src"
title = "Aura User Manual"

[output.html]
git-repository-url = "https://github.com/ronmkr/aura"
edit-url-template = "https://github.com/ronmkr/aura/edit/main/aura-docs/manual/{path}"
additional-css = ["src/aura.css"]
additional-js = []
